site_name: 瑰夏图书馆
site_author: 'AmarokIce'
site_description: '盖尔斯威特的土地上，皇家海盗瑰夏决定为居民们带来一坐只是宝库...'
copyright: Copyright © 2020-2024 AmarokIce
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AmarokIce/
      name: Github
  generator: false

nav:
- 图书馆大厅:
  - 瑰夏图书馆: index.md
  - 图书馆介绍: library.md
- D-100H:
  - 岛屿概览: d-100h/index.md
  - 地区资料:
    - 浅坡平原: d-100h/data/riat.md
    - 冷森林: d-100h/data/gailswaite.md
    - 中心城镇：马克帕克: d-100h/data/makpaco.md
  - 居民档案:
    - 米拉特尔: d-100h/people/Miratl.md
    - 席尔蒂玛: d-100h/people/Siltima.md
    - 维多利亚: d-100h/people/Victoria.md
    - 帕普斯: d-100h/people/Pappus.md
    - “阿金”: d-100h/people/Gold.md
    - 瑰夏: d-100h/people/Gousa.md
    - 帕尔森: d-100h/people/Parson.md
    - 帕里斯: d-100h/people/Paris.md
    - 梅佳斯: d-100h/people/Megace.md
    - 埃尔&埃米: d-100h/people/BroEiy.md
    - 吉米: d-100h/people/Jimi.md
    - 马克兄弟: d-100h/people/BroMark.md
    - 杰: d-100h/people/Jie.md
    - 格拉尔: d-100h/people/Glar.md
    - 米拉: d-100h/people/Miri.md
    - 伊劳雅克: d-100h/people/Illaujaq.md
- 辉宏都市: cityofhuihong/index.md
- N-14-A:
    - 岛屿概览: n-14-a/index.md
    - 地区资料:
      - 寒夜区:
        - 区域概览: n-14-a/coldnight/index.md
        - 白皑镇:
          - 小镇介绍: n-14-a/coldnight/whitetown/index.md
          - 居民档案:
            - 格兰特: n-14-a/coldnight/whitetown/Galant.md
    

theme:
  name: material
  logo: assets/ricon.png
  favicon: assets/ricon.png
  language: zh
  features:
    - header.autohide
    - navigation.footer
    - navigation.tabs
    - content.code.annotate
    - content.code.copy
  palette: 
    - scheme: default
      toggle:
        icon: material/weather-night 
        name: 关闭月亮

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 打开月亮
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - search:
      lang: zh
