site_name: 瑰夏图书馆
site_author: "Amarok Ice"
site_description: "盖尔斯威特的土地上，皇家海盗瑰夏决定为居民们带来一坐知识宝库..."
copyright: Copyright © 2020-2024 AmarokIce
extra:
    social:
        - icon: fontawesome/brands/github
          link: https://github.com/AmarokIce/
          name: Github
    generator: false

nav:
    - 图书馆大厅:
          - 瑰夏图书馆: index.md
          - 图书馆介绍: library.md
          - 图书馆贡献: libraryedit.md
    - D-100H:
          - 岛屿概览: d-100h/index.md
          - 地区资料:
                - 浅坡平原:
                      - 区域概览: d-100h/flatland/index.md
                      - 红橡木庄园: d-100h/flatland/redoak.md
                      - 石墙镇: d-100h/flatland/stonewalltown.md
                      - 皮尔镇: d-100h/flatland/pier.md

                - 冷森林:
                      - 区域概览: d-100h/coldforest/index.md
                      - 马克帕克: d-100h/coldforest/makpaco.md
                      - 盖尔斯维特森林: d-100h/coldforest/forest.md
                      - 盖尔斯维特工业园: d-100h/coldforest/izs.md
                      - 盖尔斯维特嘉年华: d-100h/coldforest/carnival.md
                      # - 阿尔斯特: d-100h/coldforest/Alster.md
                      # - 斯图尔特: d-100h/coldforest/Stuart.md

          - 居民档案:
                - 米拉特尔: d-100h/people/Miratl.md
                - 席尔蒂玛: d-100h/people/Siltima.md
                - 维多利亚: d-100h/people/Victoria.md
                - 帕普斯: d-100h/people/Pappus.md
                - “阿金”: d-100h/people/Gold.md
                - 瑰夏: d-100h/people/Gousa.md
                - 帕尔森: d-100h/people/Parson.md
                - 帕里斯: d-100h/people/Paris.md
                - 梅佳斯: d-100h/people/Megace.md
                - 埃尔&埃米: d-100h/people/BroEiy.md
                - 吉米: d-100h/people/Jimi.md
                - 马克兄弟: d-100h/people/BroMark.md
                - 杰: d-100h/people/Jie.md
                - 格拉尔: d-100h/people/Glar.md
                - 米拉: d-100h/people/Miri.md
                - 伊劳雅克: d-100h/people/Illaujaq.md
                - “瘟疫”: d-100h/people/Pestilence.md
                - 布兰登: d-100h/people/Branden.md
                - 尤朵楠: d-100h/people/Eudora.md

          - 使魔档案:
                - 克拉拉: d-100h/pet/Clara.md
                - 波利亚: d-100h/pet/Polya.md
                - 湃客: d-100h/pet/Paike.md
                - 马尔基: d-100h/pet/Marki.md
          - 吉米说: d-100h/JimiSay.md
          - 度量单位: d-100h/MeasurementUnit.md

    - 辉鸿都市:
          - 岛屿概览: cityofhuihong/index.md
          - 居民档案:
                - 夜兆白枳: cityofhuihong/people/夜兆白枳.md
                - 塞维斯: cityofhuihong/people/塞维斯.md
                - UU: cityofhuihong/people/UU.md
    - N-14:
          - 岛屿概览: N-14/index.md
          - 地区资料:
                - 寒夜区:
                      - 区域概览: N-14/coldnight/index.md
                      - 白皑镇:
                            - 小镇介绍: N-14/coldnight/whitetown/index.md
                            - 居民档案:
                                  - 格兰特: N-14/coldnight/whitetown/Galant.md
    - SN176星云:
          - 岛屿概览: SN176/index.md
          - 那瑟提: SN176/Nasetti.md

    - 天秦大同:
          - 岛屿概览: 天秦大同/index.md
          - 地区资料:
                - 乾天区: 天秦大同/area/乾天区.md
                - 坤地区: 天秦大同/area/坤地区.md
                - 震雷区: 天秦大同/area/震雷区.md
                - 巽风区: 天秦大同/area/巽风区.md
                - 坎水区: 天秦大同/area/坎水区.md
                - 离火区: 天秦大同/area/离火区.md
                - 艮山区: 天秦大同/area/艮山区.md
                - 兑泽区: 天秦大同/area/兑泽区.md

          - 聚落资料:
                - 乾天区: 天秦大同/town/乾天区.md
                - 坤地区: 天秦大同/town/坤地区.md
                - 震雷区: 天秦大同/town/震雷区.md
                - 巽风区: 天秦大同/town/巽风区.md
                - 离火区: 天秦大同/town/离火区.md
                - 艮山区: 天秦大同/town/艮山区.md
                - 兑泽区: 天秦大同/town/兑泽区.md
          - 居民档案:
                - 卡伊: 天秦大同/people/kany.md

    - L-06:
          - 岛屿概览: L06/index.md
          - 岛屿居民:
                - 古特: L06/people/古特.md

theme:
    name: material
    logo: assets/ricon.png
    favicon: assets/ricon.png
    language: zh
    features:
        - header.autohide
        - navigation.footer
        - navigation.tabs
        - content.code.annotate
        - content.code.copy

    palette:
        - scheme: default
          toggle:
              icon: material/weather-night
              name: 关闭月亮

        - scheme: slate
          toggle:
              icon: material/weather-sunny
              name: 打开月亮
    icon:
        admonition:
            note: octicons/tag-16
            abstract: octicons/checklist-16
            info: octicons/info-16
            tip: octicons/squirrel-16
            success: octicons/check-16
            question: octicons/question-16
            warning: octicons/alert-16
            failure: octicons/x-circle-16
            danger: octicons/zap-16
            bug: octicons/bug-16
            example: octicons/beaker-16
            quote: octicons/quote-16

markdown_extensions:
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.details
    - admonition

plugins:
    - search
    - search:
          lang: zh
